"""initial schema

Revision ID: 69dd234e234c
Revises: 
Created: 2026-08-26 07:07:32.227959
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '69dd234e234c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codex_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('personas', sa.JSON(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codex_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codex_versions_version'), ['version'], unique=True)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('phase', sa.Enum('CREATED', 'SENSED', 'BRIEFED', 'WRITTEN', 'SUBMITTED', 'RENDERED', 'JUDGED', 'SHIPPED', 'FAILED', name='runphase'), nullable=False),
    sa.Column('codex_version', sa.Integer(), nullable=True),
    sa.Column('credits_start', sa.Integer(), nullable=True),
    sa.Column('credits_end', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_run_date'), ['run_date'], unique=True)

    op.create_table('agent_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=False),
    sa.Column('chars_in', sa.Integer(), nullable=False),
    sa.Column('chars_out', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_calls_ok'), ['ok'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_calls_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_calls_run_id'), ['run_id'], unique=False)

    op.create_table('briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.Enum('FULL', 'SHORT', name='slottype'), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('persona_id', sa.String(length=120), nullable=True),
    sa.Column('persona_name', sa.String(length=120), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('musical_key', sa.String(length=40), nullable=True),
    sa.Column('song_form', sa.Text(), nullable=True),
    sa.Column('instrumentation', sa.Text(), nullable=True),
    sa.Column('vocal_gender', sa.String(length=4), nullable=True),
    sa.Column('style_string', sa.Text(), nullable=True),
    sa.Column('negative_tags', sa.Text(), nullable=True),
    sa.Column('diversity_vector', sa.JSON(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('lyric_hash', sa.String(length=64), nullable=True),
    sa.Column('clearance', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dropped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'slot_type', 'idx', name='uq_brief_slot')
    )
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefs_run_id'), ['run_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('picks', sa.JSON(), nullable=False),
    sa.Column('rejections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_run_id'), ['run_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('sentiment', sa.String(length=80), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('lead', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_run_id'), ['run_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.Column('state', sa.Enum('QUEUED', 'SUBMITTED', 'PENDING', 'TEXT_SUCCESS', 'FIRST_SUCCESS', 'SUCCESS', 'MIRRORED', 'FAILED', 'ABANDONED', name='jobstate'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('callbacks_seen', sa.Integer(), nullable=False),
    sa.Column('polls', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failure_kind', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_brief_id'), ['brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_task_id'), ['task_id'], unique=False)

    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.String(length=120), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.Enum('FULL', 'SHORT', name='slottype'), nullable=False),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('style_string', sa.Text(), nullable=True),
    sa.Column('negative_tags', sa.Text(), nullable=True),
    sa.Column('persona_id', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=40), nullable=True),
    sa.Column('vocal_gender', sa.String(length=4), nullable=True),
    sa.Column('style_weight', sa.Float(), nullable=True),
    sa.Column('weirdness', sa.Float(), nullable=True),
    sa.Column('audio_weight', sa.Float(), nullable=True),
    sa.Column('bpm_target', sa.Integer(), nullable=True),
    sa.Column('musical_key', sa.String(length=40), nullable=True),
    sa.Column('song_form', sa.Text(), nullable=True),
    sa.Column('lyric_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('source_audio_url', sa.Text(), nullable=True),
    sa.Column('source_image_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('spaces_key', sa.Text(), nullable=True),
    sa.Column('wav_task_id', sa.String(length=120), nullable=True),
    sa.Column('wav_url', sa.Text(), nullable=True),
    sa.Column('qc', sa.JSON(), nullable=False),
    sa.Column('qc_verdict', sa.String(length=20), nullable=True),
    sa.Column('qc_reason', sa.Text(), nullable=True),
    sa.Column('score_hook', sa.Float(), nullable=True),
    sa.Column('score_mix', sa.Float(), nullable=True),
    sa.Column('score_trend', sa.Float(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('shipped', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'audio_id', name='uq_clip_audio')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_audio_id'), ['audio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_brief_id'), ['brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_qc_verdict'), ['qc_verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_shipped'), ['shipped'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_clip_id'), ['clip_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_clip_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_shipped'))
        batch_op.drop_index(batch_op.f('ix_clips_run_id'))
        batch_op.drop_index(batch_op.f('ix_clips_qc_verdict'))
        batch_op.drop_index(batch_op.f('ix_clips_job_id'))
        batch_op.drop_index(batch_op.f('ix_clips_brief_id'))
        batch_op.drop_index(batch_op.f('ix_clips_audio_id'))

    op.drop_table('clips')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_task_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_brief_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_run_id'))

    op.drop_table('signals')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_run_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefs_run_id'))

    op.drop_table('briefs')
    with op.batch_alter_table('agent_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_calls_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_calls_role'))
        batch_op.drop_index(batch_op.f('ix_agent_calls_ok'))

    op.drop_table('agent_calls')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_run_date'))

    op.drop_table('runs')
    with op.batch_alter_table('codex_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codex_versions_version'))

    op.drop_table('codex_versions')
    # ### end Alembic commands ###
