"""stored files with retention

Revision ID: 6ad48bf109cf
Revises: 69dd234e234c
Created: 2026-08-26 07:19:50.453659
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6ad48bf109cf'
down_revision = '69dd234e234c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=400), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_stored_files_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_run_id'))
        batch_op.drop_index(batch_op.f('ix_stored_files_kind'))
        batch_op.drop_index(batch_op.f('ix_stored_files_key'))
        batch_op.drop_index(batch_op.f('ix_stored_files_expires_at'))
        batch_op.drop_index(batch_op.f('ix_stored_files_clip_id'))

    op.drop_table('stored_files')
    # ### end Alembic commands ###
